version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - ../woob/modules:/app/woob/modules  # <-- Mount host folder inside container
    environment:
      - W_ROOT=/app/woob/modules  
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
